### ISSUE TITLE
autostart if not running

### ISSUE THREAD

**Issue by lougreenwood** [jo-sm/stylelint_d#23]
It seems that eslint_d and similar will autostart if not running.

For example, if the daemon is not running, then `stylelint_d --fix` would start a new server.

Perhaps this is a feature of [`core_d`](https://github.com/mantoni/core_d.js), which is why it's missing from `stylelint_d`?

**Comment by jo-sm** [comment]
Hi @lougreenwood, sorry but I'm a little confused - do you mean that `stylelint_d` is not automatically starting when you run a command? If so, can you provide a more complete reproducible example for me please, as well as provide your environment (OS, Node version, etc.)? The daemon [should automatically start](https://github.com/jo-sm/stylelint_d/blob/3ff599c946a4be78ae53878ff4f2beac9659d90b/src/client.ts#L247-L252), but there might be an error happening that I'm not properly handling.

**Comment by jo-sm** [comment]
@lougreenwood I'm going to go ahead and assume this is working as expected and going to close this issue, but please feel free to reopen if you can provide additional details about the automatic daemon starting not working as expected.
