### ISSUE TITLE
Allow input to be passed in though stdin

### ISSUE THREAD

**Issue by chrishoage** [jo-sm/stylelint_d#3]
`eslint_d` allows for input though stdin, this allows for `background` mode in sublime linter to work (as SublimeLinter will pass in the current buffer of the file) 

With out the ability to use `stdin` background mode always uses the saved version of the file, not the version in the buffer.

**Comment by jo-sm** [comment]
I updated `stylelint_d` to support input via `stdin` using the `--stdin` flag. If you want to use it standalone, you'll need to pass in either the config file location, or the file location, with the `--config` or `--file` flags respectively.
