### ISSUE TITLE
Can't seem to run it

### ISSUE THREAD

**Issue by woble** [jo-sm/stylelint_d#5]
Hi, I stumbled on this and decided to try it. Installed it globally and tried running both `stylelint_d` and `stylelint_d start`, but to no avail. It just sits there without any prompts or errors.

Tried `stylelint_d --stdin --file foo.css --config stylelint.json`, but that as well just sits there and does nothing. Only way to stop the process is through `Ctrl+C` or kill it in task manager.

I also tried the SublimeLinter plugin, which alas doesn't do anything either. SublimeLinter debug mode returns this:

```
SublimeLinter: stylelint_d: FILE.pcss ['C:\\Users\\USER\\AppData\\Roaming\\npm\\stylelint_d.cmd', '--stdin', '--file', '@', '--config', 'PATH_TO_CONFIG']
```

I am on Windows 7 64bit and following node/npm.

```
{ npm: '3.10.5',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.3.1',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.57',
  zlib: '1.2.8' }
```

**Comment by jo-sm** [comment]
Ahh I didn't write it with Windows support in mind (I have no way of testing as I use Mac). 

The problem is that I create a socket file to listen to, which is only allowed in Unix. I'm guessing that Node itself doesn't really return back any errors when attempting to listen to a file socket on Windows. In any case, I'll update it to listen to a local port. 

Also note, you shouldn't send the `--config` flag in this case, since you're supplying the filename via Sublime. Sending the config parameter in that way will most likely error out, or will return nothing, since it's preferentially used versus the `--file` flag.

**Comment by woble** [comment]
Just tried on a Mac and it does indeed work just fine. I do still have to provide the `"args": [ "--config", "PATH_TO_CONFIG" ]` when settings up `stylelint_d` in SublimeLinter on user or project level. So I don't really understand what you meant with not sending `--config` flag.

**Comment by jo-sm** [comment]
Is `PATH_TO_CONFIG` the actual config path that SublimeLinter replaces?

**Comment by woble** [comment]
Nah, it's just so I didn't have to type the whole path here, which is `${project}/../build/plugins/gulp-tslint/tslint.json`. The `{project}` is the only token that is being replaced by SublimeLinter.

**Comment by jo-sm** [comment]
Huh, that's weird, I'm surprised that works even when supplied `PATH_TO_CONFIG` as the `--config` flag value. Glad to hear it is though!

**Comment by jo-sm** [comment]
@woble I updated the code to use a TCP socket in e41121da6a3fd8888fc522a042c84d60471e7dce. Can you download the latest `stylelint_d` (`1.0.7`) and see if it works on Windows?

**Comment by woble** [comment]
Tested on Windows 10 Pro, works. 👍 Will test on Windows 7 tomorrow.

**Comment by woble** [comment]
Hmm, I am not sure if it's Windows 7, or something on my work machine (maybe antivirus; can't disable it unfortunately because corp policy) but I can't seem to get `stylelint_d` to work any more.

#### Things I've tried
- Reinstalling nodejs (LTS version) and some of the global packages that I use.
- Fresh Sublime Text 3 (Dev 3120) with only a few required packages, `SublimeLinter`, `SublimeLinter-contrib-tslint`, `SublimeLinter-contrib-stylelint_d`, `Syntax Highlighting for PostCSS`, `TypeScript`.
- Also installed `SublimeLinter-contrib-stylelint` to test if it breaks anything.

#### Observed behaviour
- Run `stylelint_d start`.
- Open ST project with linters (`tslint`, `stylelint_d`) setup through the project file.
- No files are open. SublimeLinter is in debug mode.
- Open `.ts` file — `tslint` initiated. Linting works and there's output in Sublime console.
- Open `.pcss` file — `stylelint_d` initiated. Linting doesn't work and no console output.
- Switch to the open `.ts` file. Linting doesn't work. No console output.

It looks as if the moment `stylelint_d` is run once, SublimeLinter stops working without any errors or dumps in console.

Swapping `stylelint_d` for `stylelint` in the same scenario works just fine.

**Comment by jo-sm** [comment]
What version of `SublimeLinter-contrib-stylelint_d` do you have?

**Comment by woble** [comment]
The latest version.

**Comment by jo-sm** [comment]
Since it looks like `stylelint_d` is working, let's move this to `SublimeLinter-contrib-stylelint_d`...

**Comment by woble** [comment]
Appears that after we switched from Symantec to Sophos, stylelint_d started working in Suiblime on Windows 7 again. \o/
