### ISSUE TITLE
Deprecations is undefined

### ISSUE THREAD

**Issue by jo-sm** [jo-sm/stylelint_d#9]
From https://github.com/jo-sm/SublimeLinter-contrib-stylelint_d/issues/7#issuecomment-299831487:

Hi @jo-sm 

I am again back to front-end development and again the linter stopped working. Here is what i got when hitting stylelint_d in command.

```
 memo.outputs[memo.currentIndex][memo.currentType].push(i);
                                           ^

TypeError: Cannot read property 'deprecations' of undefined
    at data.reduce.start (C:\Users\User\AppData\Roaming\npm\node_modules\stylelint_d\bin\stylelint_d.js:128:44)
    at Array.reduce (native)
    at Socket.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\stylelint_d\bin\stylelint_d.js:103:31)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by jo-sm** [comment]
@sethstha I migrated the issue to the `stylelint_d` repo. 

Can you give me some additional information, like the `stylelint_d` version, `stylelint` version, and the CSS file you're using? That will make it a lot easier to track down this issue.

**Comment by sethstha** [comment]
Hey @jo-sm 

Here is the complete error log thrown on command prompt.
```
C:\xampp\htdocs\flash-pro\wp-content\themes\flash-pro\scss\themes>stylelint_d _timeline.scss
C:\Users\User\AppData\Roaming\npm\node_modules\stylelint_d\bin\stylelint_d.js:128
            memo.outputs[memo.currentIndex][memo.currentType].push(i);
                                           ^

TypeError: Cannot read property 'deprecations' of undefined
    at data.reduce.start (C:\Users\User\AppData\Roaming\npm\node_modules\stylelint_d\bin\stylelint_d.js:128:44)
    at Array.reduce (native)
    at Socket.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\stylelint_d\bin\stylelint_d.js:103:31)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```
Here are the information you needed.
**stylelint_d: 1.1.1**
**stylelint: 7.10.1**

This is error with every CSS or SCSS file. And here is the current file i am working on.



Thanks

**Comment by sethstha** [comment]
I found the actual cause of this issue. If we don't supply configuration file on the root directory of project, this error is occurring.

**Comment by jo-sm** [comment]
Where is the configuration file in relation to `_timeline.scss`?

**Comment by sethstha** [comment]
This is the structure of my directly.

|--assets|
              |--scss
                        |--_timeline.scss
|--.stylelintrc

Providing configuration file on the command doesn't throw error. I think when configuration is not provided or put on directly it should load the default configuration.

**Comment by jo-sm** [comment]
Ah, so let me make sure I understand correctly.

The layout of your directory is this:

```
assets/
    scss/
        _timeline.scss
        .stylelintrc
```

And when you attempt to run `stylelint_d` on `_timeline.scss`doing something like this:

```
$ stylelint_d assets/scss/_timeline.scss
```

It returns the error you're receiving. 

If that's the case, I think I know what might be causing the issue, but I'll need to do a little investigation to be sure.

**Comment by jo-sm** [comment]
Heya @sethstha just checking in again. Is the previous comment I made accurate?

**Comment by sethstha** [comment]
Hii @jo-sm 

Sorry for the delay.

This is how the my directory is
```
theme-directory/
     .stylelintrc
     assets/
          scss/
              _timeline.scss
```

You are confused here. Let me explain it to you. When `.stylelintrc` file is present in root directory. It works fine. But when there is no `.stylelintrc` file in root directory. It is throwing the error I mentioned above.
I think it should load default configuration file or throw error saying no configuration file provided.

Hope this clears your confusion.

**Comment by jo-sm** [comment]
Hey @sethstha, I updated some code internally, and ran a test without a configuration and was able to get an error stating the configuration file is missing:

```
@ /assets [master] > stylelint_d css/test.css 
Could not lint file: Error: No configuration provided for /assets/css/test.css
```

I'll close this as fixed, but let me know if you're still running into this issue after upgrading to 1.1.2.
